name: Tests
on:
  push:
    branches:
      - main
      - master
      - dev
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  test:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Running Tests
        run: |
          make test
